<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Features.Application\Features.Application.csproj" />
    <ProjectReference Include="..\Features.Infrastructure\Features.Infrastructure.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\MySaaS.BuildingBlocks\MySaaS.BuildingBlocks.csproj" />
  </ItemGroup>
  
</Project>
